-- No-op intencional. NÃO reintroduza SQL aqui.
--
-- Histórico: esta migration foi escrita para bancos gerenciados por `prisma db push`,
-- onde 20260625105121_init nunca chegou a ser registrada em _prisma_migrations. Ela
-- repetia, byte a byte, o mesmo SQL daquela migration (as 5 colunas de comando em App,
-- as tabelas AppMetric e SystemSettings e o índice de AppMetric), para que o rebuild da
-- tabela App em 20260716215020_add_projects copiasse esses dados em vez de descartá-los.
--
-- O efeito colateral era que a cadeia de migrations parava de aplicar num banco limpo:
--
--     $ npx prisma migrate deploy
--     Error: P3018 ... Migration name: 20260716200000_reconcile_app_drift
--     Database error: duplicate column name: buildCommand
--
-- ou seja, nenhuma instalação nova conseguia criar o banco por migrations, e nenhum
-- banco existente conseguia sair do `db push` para o `migrate deploy`.
--
-- Como 20260625105121_init já contém exatamente este SQL e vem antes na ordem, o passo
-- correto aqui é não fazer nada. O arquivo continua existindo (e o nome continua no
-- histórico) porque removê-lo quebraria qualquer banco que já a tenha registrado.
--
-- Bancos antigos criados por `db push` não têm histórico nenhum: o update.sh os registra
-- uma única vez com `prisma migrate resolve --applied`, que grava só metadados e não
-- toca em dado nenhum.
SELECT 1;
